#!/usr/bin/env python3
"""Deterministic helpers for the token-optimized Anak extraction pipeline.

This module does NOT decide legal sections. All section/boundary decisions are
made by the Codex model. This module only performs mechanical text handling:

  1. clean        Strip the repeated Mahkamah Agung boilerplate (disclaimer,
                  page headers/footers, form-feeds) and emit a stable,
                  line-numbered rendering of the source for the model to point
                  into.
  2. expand       Given the model's per-section pointers (line ranges) or short
                  literal values, slice the exact contiguous excerpts from the
                  cleaned text and assemble the Anak.json-conforming output.

Span/offset extraction (the model emits pointers, a deterministic step expands
them) is the standard token-saving technique from extractive QA / Pointer
Networks: output is O(boundaries), not O(content). It preserves "exact
contiguous source excerpt" fidelity because the excerpt is sliced verbatim from
the source rather than regenerated by the model.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

# The 31 section keys, in schema order.
SECTION_KEYS = [
    "judul", "nomor_putusan", "irah_irah", "nama_pengadilan_negeri",
    "keterangan_perkara", "nama_lengkap", "tempat_lahir", "umur_tanggal_lahir",
    "jenis_kelamin", "kebangsaan", "tempat_tinggal", "agama", "pekerjaan",
    "penangkapan", "penahanan", "tuntutan", "dakwaan", "saksi", "ahli",
    "terdakwa", "surat", "petunjuk_barang_bukti", "fakta_hukum",
    "pertimbangan_hukum", "amar_putusan", "hari", "tanggal", "tahun",
    "siapa_yang_memutus", "panitera_pengganti", "tanda_tangan_majelis",
]

# Lines that are exactly (after strip) one of these are repeated page furniture.
_EXACT_BOILERPLATE = {
    "mahkamah agung republik indonesia",
    "direktori putusan mahkamah agung republik indonesia",
    "putusan.mahkamahagung.go.id",
    "disclaimer",
}

# Lines that *start with* one of these are repeated disclaimer/footer text.
_PREFIX_BOILERPLATE = (
    "kepaniteraan mahkamah agung republik indonesia berusaha",
    "pelaksanaan fungsi peradilan. namun dalam hal-hal tertentu",
    "dalam hal anda menemukan inakurasi",
    "email : kepaniteraan@mahkamahagung.go.id",
)

# Page-footer pattern: "Halaman 3 dari 13 Putusan Nomor 1/Pid.Sus-Anak/2026/PN Bdw"
_PAGE_FOOTER = re.compile(r"^Halaman\s+\d+\s+dari\s+\d+\s+Putusan\s+Nomor", re.IGNORECASE)
# Bare trailing page marker like "Halaman 1" on its own line.
_BARE_PAGE = re.compile(r"^Halaman\s+\d+\s*$", re.IGNORECASE)


def clean_lines(raw_text: str) -> list[str]:
    """Return source lines with repeated MA boilerplate removed.

    Conservative and line-based: only lines that clearly match known repeated
    page furniture are dropped. Real decision content is never matched by these
    rules. Form-feed characters are stripped. The result is the text the model
    points into; every kept line keeps its original spelling/punctuation/OCR.
    """
    out: list[str] = []
    for raw_line in raw_text.replace("\f", "\n").split("\n"):
        line = raw_line.rstrip("\r")
        stripped = line.strip()
        if stripped == "":
            # Collapse runs of blank lines created by removed furniture.
            if out and out[-1] == "":
                continue
            out.append("")
            continue
        low = stripped.lower()
        if low in _EXACT_BOILERPLATE:
            continue
        if any(low.startswith(p) for p in _PREFIX_BOILERPLATE):
            continue
        if _PAGE_FOOTER.match(stripped) or _BARE_PAGE.match(stripped):
            continue
        out.append(line)
    # Trim leading/trailing blank lines.
    while out and out[0] == "":
        out.pop(0)
    while out and out[-1] == "":
        out.pop()
    return out


def render_numbered(lines: list[str]) -> str:
    """Render cleaned lines with 1-based line numbers for the model prompt."""
    width = len(str(len(lines)))
    return "\n".join(f"{str(i + 1).rjust(width)}| {line}" for i, line in enumerate(lines))


def _snap_literal(value: str, cleaned: str) -> str:
    """Return the exact source substring for a short literal value.

    Span slices are verbatim by construction; only short `text` literals can
    drift (e.g. a name retyped with different internal spacing). If the literal
    is not already a verbatim substring, match it against the cleaned text with
    flexible whitespace; if exactly one region matches, snap to that exact
    source substring. Otherwise keep the model's value unchanged.
    """
    if value in cleaned:
        return value
    tokens = [t for t in re.split(r"\s+", value.strip()) if t]
    if not tokens:
        return value
    pattern = r"\s+".join(re.escape(t) for t in tokens)
    matches = re.findall(pattern, cleaned)
    if len(matches) == 1:
        return matches[0]
    return value


def _slice_lines(lines: list[str], start: int, end: int) -> str:
    """Inclusive 1-based slice joined with newlines."""
    start = max(1, start)
    end = min(len(lines), end)
    if end < start:
        return ""
    return "\n".join(lines[start - 1:end]).strip("\n")


def expand(spans: dict, lines: list[str]) -> tuple[dict, list[str]]:
    """Turn the model's pointer/literal spans into section excerpt arrays.

    `spans` shape (per the prompt contract): {"sections": {<key>: <spec>}} where
    <spec> is one of:
        {"lines": [[start, end], ...]}   # line-range pointers (preferred, big)
        {"text":  ["literal value", ...]} # short literal values
        {"empty": true}                   # absent in source
    Returns (sections_dict, empty_section_keys).
    """
    section_specs = spans.get("sections", {})
    cleaned = "\n".join(lines)
    sections: dict[str, list[str]] = {}
    for key in SECTION_KEYS:
        spec = section_specs.get(key, {})
        values: list[str] = []
        if isinstance(spec, dict):
            if spec.get("lines"):
                for pair in spec["lines"]:
                    if not isinstance(pair, (list, tuple)) or len(pair) != 2:
                        raise ValueError(f"{key}: bad line range {pair!r}")
                    excerpt = _slice_lines(lines, int(pair[0]), int(pair[1]))
                    if excerpt:
                        values.append(excerpt)
            elif spec.get("text"):
                for item in spec["text"]:
                    s = str(item)
                    if s.strip():
                        values.append(_snap_literal(s, cleaned))
        sections[key] = values
    empty = [k for k in SECTION_KEYS if not sections[k]]
    return sections, empty


def build_output(spans: dict, raw_text: str, source_file: str, source_path: str) -> dict:
    lines = clean_lines(raw_text)
    sections, empty = expand(spans, lines)
    sha = hashlib.sha256(raw_text.encode("utf-8")).hexdigest()
    return {
        "status": "completed",
        "source_file": source_file,
        "source_path": source_path,
        "source_sha256": sha,
        "sections": sections,
        "empty_sections": empty,
        "method": "codex_manual_extractive",
    }


def _read_text(path: Path) -> str:
    # Sources may carry a BOM; keep raw content otherwise intact.
    return path.read_text(encoding="utf-8-sig")


def cmd_clean(args: argparse.Namespace) -> int:
    raw = _read_text(Path(args.source))
    lines = clean_lines(raw)
    sys.stdout.write(render_numbered(lines))
    sys.stdout.write("\n")
    return 0


def cmd_expand(args: argparse.Namespace) -> int:
    raw = _read_text(Path(args.source))
    spans = json.loads(Path(args.spans).read_text(encoding="utf-8-sig"))
    source_file = args.source_file or Path(args.source).name
    source_path = args.source_path or args.source.replace("\\", "/")
    output = build_output(spans, raw, source_file, source_path)

    # Structural validation (dependency-free) against the Anak.json contract.
    problems = validate_output(output)
    if problems:
        sys.stderr.write("VALIDATION FAILED:\n" + "\n".join(problems) + "\n")
        return 2

    Path(args.out).write_text(
        json.dumps(output, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    # Emit a compact summary for the launcher to log/checkpoint.
    summary = {
        "source_file": output["source_file"],
        "source_path": output["source_path"],
        "source_sha256": output["source_sha256"],
        "output": args.out.replace("\\", "/"),
        "status": output["status"],
        "method": output["method"],
        "empty_sections": output["empty_sections"],
    }
    sys.stdout.write(json.dumps(summary, ensure_ascii=False))
    sys.stdout.write("\n")
    return 0


def validate_output(output: dict) -> list[str]:
    problems: list[str] = []
    for field in ("status", "source_file", "source_path", "source_sha256",
                  "sections", "empty_sections", "method"):
        if field not in output:
            problems.append(f"missing top-level field: {field}")
    if output.get("method") != "codex_manual_extractive":
        problems.append("method must be codex_manual_extractive")
    if not re.fullmatch(r"[a-fA-F0-9]{64}", output.get("source_sha256", "")):
        problems.append("source_sha256 must be 64 hex chars")
    sections = output.get("sections", {})
    keys = list(sections.keys())
    if keys != SECTION_KEYS:
        missing = [k for k in SECTION_KEYS if k not in sections]
        extra = [k for k in keys if k not in SECTION_KEYS]
        if missing:
            problems.append(f"missing section keys: {missing}")
        if extra:
            problems.append(f"unexpected section keys: {extra}")
    for k, v in sections.items():
        if not isinstance(v, list) or any(not isinstance(x, str) or not x for x in v):
            problems.append(f"section {k} must be an array of non-empty strings")
    computed_empty = sorted(k for k in SECTION_KEYS if not sections.get(k))
    if sorted(output.get("empty_sections", [])) != computed_empty:
        problems.append("empty_sections does not match empty section arrays")
    return problems


def main(argv: list[str] | None = None) -> int:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")
        except (AttributeError, ValueError):
            pass
    parser = argparse.ArgumentParser(description="Anak extraction deterministic helpers")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_clean = sub.add_parser("clean", help="Emit line-numbered, boilerplate-free source")
    p_clean.add_argument("source")
    p_clean.set_defaults(func=cmd_clean)

    p_expand = sub.add_parser("expand", help="Expand model spans into the output JSON")
    p_expand.add_argument("--source", required=True)
    p_expand.add_argument("--spans", required=True)
    p_expand.add_argument("--out", required=True)
    p_expand.add_argument("--source-file", default="")
    p_expand.add_argument("--source-path", default="")
    p_expand.set_defaults(func=cmd_expand)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
